default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  database: Glados_development
  username: glados_master
  password: 'PrMjBaxIGl7PRmTEAzFu'
  host: 'glados.cdn30frlb8j8.us-east-1.rds.amazonaws.com'
  port: 5432

development:
  <<: *default
  
test:
  <<: *default

production:
  <<: *default